# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Show.create(name: 'The Next Iron Chef', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", widget_key: '3140b43d-c0c4-4ca9-a049-30bbd4abb481')
Show.create(name: "Rachel Ray's Week in a Day", description: "If you've ever wished there was an easier and better way to get dinner on the table every night, you need Rachael Ray's Week in a Day. The woman who taught America how to make a meal in 30 minutes is back with an even bigger promise: one day of cooking, up to five days of eating! In every episode, Rachael will show you five meals you can put together in a single day. So when you come home from a hard day of work, the hard work in the kitchen's already done. Using the recipes, strategies, and tips from Week in a Day, you can eat well every night even on those days when the clock is working against you.", widget_key: 'f6acc44f-41de-4552-8973-d5d051de8529')
Show.create(name: 'Restaurant Stakeout', description: "Willie Degel is known for running a tight ship at his restaurants. His secret: cameras canvassing every inch of his restaurant, allowing him to keep a close eye on his floor, staff and patrons. Restaurant Stakeout follows as Willie takes his practices to troubled restaurateurs looking to find and rectify the hidden problems that lie within their establishments.", widget_key: '55027e55-db64-4807-b406-13671b8c76f4')
Show.create(name: 'The Pioneer Woman', description: "Take one sassy former city girl, her hunky rancher husband and a band of adorable kids, an extended family, cowboys, 3000 wild mustangs, a herd of cattle and one placid basset hound and you have The Pioneer Woman. The Pioneer Woman is an open invitation into Ree Drummond's life: The award-winning blogger and best-selling cookbook author comes to Food Network and shares her special brand of home cooking, from throw-together suppers to elegant celebrations. The series, set against the incredible story of life at home on the range, is the next best thing to actually sitting on a stool in Ree's kitchen.", widget_key: '2fbcfc64-4f6f-4a07-91d0-eed36c01e52b')
Show.create(name: 'Chopped', description: "Chopped is a cooking competition show that's all about skill, speed and ingenuity where four up-and-coming chefs compete before a panel of three expert judges and take everyday items and turn them into an extraordinary three-course meal. Course by course, the chefs will be \"chopped\" from the competition until only one winner remains. The challenge? They have seconds to plan and 30 minutes to cook an amazing course with the basket of mystery ingredients given to them moments before the clock starts ticking! And the pressure doesn't stop there. Once they've completed their dish, they've got to survive the Chopping Block where our three judges are waiting to be wowed and not shy about voicing their culinary criticisms! Our host, Ted Allen, leads this high energy, high-pressure show which will have viewers rooting for a winner and cheering for the losers. CHOPPED is a game of passion, expertise and skill and in the end, only one chef will survive the Chopping Block. Who will make the cut? The answer is on Chopped!", widget_key: 'e5d74fff-2dc2-48b4-98e8-a16f63226c2c')